id: swift-webview-config-fraudulent-site-warning-swift
language: swift
severity: warning
message: >-
  Webviews were observed that explicitly opt ouf of the WKWebView
  fraudulent site warnings. Consider enabling such functionality, to better
  protect your users from fraud/malware.
note: >-
  [CWE-272]: Least Privilege Violation
  [REFERENCES]
       https://mas.owasp.org/MASVS/controls/MASVS-PLATFORM-2/
utils:
  match_isFraudulentWebsiteWarningEnabled:
    kind: assignment
    all:
      - has:
          stopBy: end
          kind: navigation_expression
          has:
            stopBy: end
            kind: simple_identifier
            pattern: $R
      - has:
          stopBy: end
          kind: navigation_suffix
          has:
            stopBy: end
            kind: simple_identifier
            regex: "^isFraudulentWebsiteWarningEnabled$"
      - has:
          kind: boolean_literal
          regex: "^false$"
      - follows:
          stopBy: end
          kind: property_declaration
          has:
            stopBy: end
            kind: pattern
            has:
              kind: simple_identifier
              pattern: $R
      - not:
          precedes:
            kind: assignment
            has:
              kind: boolean_literal
              regex: "false$|true"
      - not:
          follows:
            kind: assignment
            has:
              stopBy: end
              kind: boolean_literal
              regex: "^false"
  match_simple_identifier:
    kind: assignment
    all:
      - has:
          stopBy: end
          kind: navigation_expression
          has:
            stopBy: end
            kind: simple_identifier
            pattern: $R
      - has:
          stopBy: end
          kind: navigation_suffix
          has:
            stopBy: end
            kind: simple_identifier
            regex: "^isFraudulentWebsiteWarningEnabled$"
      - has:
          kind: simple_identifier
      - follows:
          stopBy: end
          kind: property_declaration
          has:
            stopBy: end
            kind: pattern
            has:
              kind: simple_identifier
              pattern: $R
      - not:
          precedes:
            kind: assignment
            has:
              kind: boolean_literal
              regex: "false$|true"
      - not:
          follows:
            kind: assignment
            has:
              stopBy: end
              kind: boolean_literal
              regex: "^false"

rule:
  any:
    - matches: match_isFraudulentWebsiteWarningEnabled
    - matches: match_simple_identifier
